apiVersion: v1
kind: Namespace
metadata:
  name: devops-data-staging
  labels:
    team: data
    environment: staging
    managed-by: platform-team
  annotations:
    team.contact: "data-team@company.com"
    purpose: "Data processing staging environment"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-staging-quota
  namespace: devops-data-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "5"
    secrets: "15"
    configmaps: "15"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: data-staging-limits
  namespace: devops-data-staging
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
