# Kubernetes Namespace Request
# Team: christeam
# Environment: dev
# Requested: 2025-10-25
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-christeam-dev
  labels:
    team: christeam
    environment: dev
    managed-by: platform-team
    created-via: self-service
  annotations:
    team.contact: "chris@team.nl"
    purpose: "christest"
    requested-date: "2025-10-25"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: christeam-dev-quota
  namespace: devops-christeam-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    persistentvolumeclaims: "5"
    services: "10"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: christeam-dev-limits
  namespace: devops-christeam-dev
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container